/* do not change this file, it is auto generated by storybook. */

import { start, updateView } from "@storybook/react-native";

import "@storybook/addon-ondevice-controls/register";
import "@storybook/addon-ondevice-actions/register";

const normalizedStories = [
  {
    titlePrefix: "",
    directory: "./src",
    files: "**/*.stories.?(ts|tsx|js|jsx)",
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
    // @ts-ignore
    req: require.context(
      "../src",
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
    ),
  },
];

declare global {
  var view: ReturnType<typeof start>;
  var STORIES: typeof normalizedStories;
}

const annotations = [
  require("./preview"),
  require("@storybook/react-native/preview"),
];

(
  globalThis as typeof globalThis & {
    STORIES: typeof normalizedStories;
    view: ReturnType<typeof start>;
  }
).STORIES = normalizedStories;

// @ts-ignore
module?.hot?.accept?.();

const globalObj = globalThis as typeof globalThis & {
  STORIES: typeof normalizedStories;
  view: ReturnType<typeof start>;
};

if (!globalObj.view) {
  globalObj.view = start({
    annotations,
    storyEntries: normalizedStories,
  });
} else {
  updateView(globalObj.view, annotations, normalizedStories);
}

export const view = globalObj.view;
